### ISSUE TITLE
VSCode: elseif vs Semantic Kernel :elsif

### ISSUE THREAD

**Issue by BartNetJS** [microsoft/prompty#100]
In my promty file, when using the VSCode extension i have to use elseif syntax:

```
{% if change > 0 %}
  positive.
{% **elseif** change < 0 %}
  negative.
{% else %}
 neutral.
{% endif %}
```

And for Symatic Kernel (version 1.22.0-alpha) I have to use elsif to get it working:

```
{% if change > 0 %}
  positive.
{% **elsif** change < 0 %}
  negative.
{% else %}
   neutral.
{% endif %}
```

Is this an issue with prompty extension, or semantic kernel?

Prompty extention gives: unknown block tag: elsif

And the other syntax in Symantic Kernel: "The template could not be parsed:\r\n'{% endif %}' was expected at (35:3)\nSource:\n  {% elseif change < 0 %}"

**Comment by sethjuarez** [comment]
Ok - so we found that template rendering tends to be spotty across language implementations - we found the intersection between liquid and jinja2 created the best subset. In general, prompty doesn't really care about template language. BUT, for the SK implementation we went with liquid. So even though it _feels_ the same as jinja2 - its actually liquid.
