### ISSUE TITLE
[Bug] Support for Sample in external file is not working

### ISSUE THREAD

**Issue by injeniero** [microsoft/prompty#135]
Per the spec, you can provide a file for the `sample` field, but I tried with json and yaml and it doesn't load it, neither in the VS Extension nor in python runtime.

```yaml
...
sample: test_1.json
```

```yaml
...
sample: test_1.yaml
```

**Comment by sethjuarez** [comment]
In this case it reads this as a string. If you change it to `${file:test_1.json}` then it should load it up as a dictionary that is then expanded into the sample variables. Let me know if this works.

**Comment by injeniero** [comment]
It works! Thanks! Is this documented?
