### ISSUE TITLE
Extension installs but doesn't allowing running prompty

### ISSUE THREAD

**Issue by brhall13** [microsoft/prompty#18]
I am able to install the extension, create a .prompty file, and create prompt flow code from them. However, I am unable to use or see any of the top buttons, such as the tests, batch runs, etc.
![IMG_5961](https://github.com/microsoft/prompty/assets/106448224/3aa72ea9-2538-4e1b-b72a-8f854e363054)
^ Expected
<img width="362" alt="Screenshot 2024-06-11 at 4 34 37 PM" src="https://github.com/microsoft/prompty/assets/106448224/e5d82198-3257-4413-95c5-fd0651c0962c">
^ Current

**Comment by sethjuarez** [comment]
Got it - those come from the [PromptFlow extension](https://marketplace.visualstudio.com/items?itemName=prompt-flow.prompt-flow). If you install that extension, you should see those at the top. The [Prompty extension](https://marketplace.visualstudio.com/items?itemName=ms-toolsai.prompty) has a play button to run them without PromptFlow as well:

![image](https://github.com/microsoft/prompty/assets/115409/497353b4-a687-4f8f-9a5c-e65b9ea3be44)

Let me know if this works!

**Comment by brhall13** [comment]
That worked! Thanks for the help and quick response!
