### ISSUE TITLE
Examples of tool definition and usage.

### ISSUE THREAD

**Issue by Tyler-R-Kendrick** [microsoft/prompty#28]
## Problem statement

My team wants to use prompty tool invocation, but we are having difficulty finding documentation on this feature.
We saw that you demoed tool usage around files in the build presentation; but, we didn't see how those tools were defined - or what the limitations of the template syntax were for tool invocation.

## Solution Exploration

It appears that jinja2 is specified as the only supported template engine. However, the build demo shows a different template syntax for tool invocation in the yaml portion of a prompty file. The line using string interpolation and file invocation appears to be currently undocumented. It is also unclear if tools other than "file" are able to be registered (or if there are other default tools).

The line I'm referring to reads approx:

```yaml
sample:
  research: ${file:research.json}
```
There are many open questions about this syntax. For example:

* How do tools take in multiple arguments?
* What are the restrictions for tool names (can they have dashes, spaces, etc?)
* What are the restrictions for arguments (do they support json object syntax, strings?)

No information about tool invocation was discovered in the markdown portion of the prompt file. Though jinja template syntax should be sufficient, it is uncertain how tools are loaded for execution in this scenario.

## The Ask

Provide documentation to clarify how to provide built-in and custom tool invocation for both the yaml and markdown portions of the prompty file where the scenarios are currently supported.

**Comment by sethjuarez** [comment]
OH MAN - I am sorry I missed this! In this case the only input to this prompty becomes the `research` parameter. In general, whatever shape you pass in here becomes the input type. There is no concept of a `tool` in prompty: each file will ever only represent a single LLM call. But maybe I am misunderstanding the question a bit?

**Comment by Tyler-R-Kendrick** [comment]
Sorry for the confusion, Seth.

My question around tool usage and limitations is around the use of the word "file" there, not yaml syntax.
Based on the usage, it appears that there is a separate llm tool (or plugin) registered and known by Prompty called "file".
This file tool runs basic io when its specified in a prompt, with the parameter "research.json". This file tool is undocumented - as are any other tools known by or built into Prompty like "file".

Furthermore, this syntax is using a kind of string interpolation syntax not defined by the jinja template syntax specified in the docs. ```${file: research.json}``` would instead be written ```{% file("research.json") %}``` if you were using jinja2. So, I am curious what standard is being used for the template invocation of tools (or plugins) like ```file```.

Lastly, as of the latest checkin, tool sections are described in the Prompty spec as valid configurations (for a model config), but there is no example of how to use or register them for execution in the vscode extension. See lines [202 and 213 here](https://github.com/microsoft/prompty/blob/cd611e7b6f827a4b322681664ab824ae22df86e2/Prompty.yaml)

**Comment by sethjuarez** [comment]
I get the question now. I think the answer is really a two-parter.

## On Prompty Property Expansion
Generally, fully specified prompty files could have a lot of yaml markup. We added the ability to write some of that markup in json (I should add yaml too I think) as a separate file that you could then expand into the given property location. Pulling in a specification for the right tools is an example of that: specifying tools can tend to be very verbose so we added the ability write the entire structure into a file and then pull it in via `${file:mytools.json}`. In this case it just expands that markup into the prompty file to then pass into the OpenAI client constructor. This is also the case with the `${env:MY_ENV_VAR}` construction: it basically replaces that portion of the prompty file with whatever is in the `MY_ENV_VAR` environment variable. In both cases these constructs are used to clean up the prompty file fontmatter markup by providing substitution functionality.

## On Tool/Function Calling
Prompty was ever only designed to represent a _single_ LLM call. In the case of tool/function calling, most implementations represent at least _2 LLM calls_:

```mermaid
sequenceDiagram
    Code->>LLM: Given these function defs and prompt + query, what should I call?
    LLM-->>Code: Call these functions for me
    Code-->>LLM: I called these functions and added the response to the history - what now?
    LLM->>Code: Here is the final response
```
The intermediate calls between the LLM and your code are often hidden in whatever orchestrator you are using (hence the dashed lines). As far as prompty is concerned, this violates the "single LLM call" principle. So with prompty, the dev is in charge of looking at the requested function call, calling the methods and then (using either the same or separate prompty file) executing the second LLM call. In our opinion this gives control back to the developer (thus making this process easier to control/debug).

Let me know if this makes sense or you have other thoughts.

**Comment by Tyler-R-Kendrick** [comment]
This is much more clarifying. Rather than referring to "file" as a tool, it would be more appropriate to call it a "property expander"?

I didn't realize you had one for ```env``` as well. Is there a "web" one, or would using file allow web requests as well?
Whatever you intend to call these things, it would be very helpful if they could be enumerated and have their syntax documented as well (since they're not in the spec file and don't adhere to jinja2 formatting).

Are these things extensible? I could see customers wanting to load data from an Azure or AWS storage account in their samples, but don't anticipate the PG Team supporting all customer loading scenarios out-of-the-box.
If "web" doesn't exist for "property expansion", am I able to make one?

**Comment by sethjuarez** [comment]
Great observations - love the idea of "property expander'. In general, there are only two at the moment `file` and `env`. For `env` you can use the following syntax:

```yaml
config: ${env:SOME_ENV_THING:value_if_not_exists}
```
There currently is not a web one - it sounds like a great idea but my sense is I should probably defer fetching to the dev and populating via the runtime. I am working on making the docs better too!
