### ISSUE TITLE
Max_tokens output limitation

### ISSUE THREAD

**Issue by fjuradom98** [microsoft/prompty#32]
I am using the gpt4 model which has as output 4096. From the prompty file in the max_tokens parameter I have 4096.
I have the python script that loads the prompty file and the credentials, but the output does not reach 4096, but it should.

What suggestions or recommendations or any additional settings I should check?

  parameters:
    max_tokens: 4096

**Comment by sethjuarez** [comment]
Weird - so is it stopping mid-word or is it reaching the stop tokens?

**Comment by fjuradom98** [comment]
Stops and cuts the output without reaching the 4096 output limit

**Comment by sethjuarez** [comment]
Got it - that sounds like a bug - is this in the extension or in code?

**Comment by fjuradom98** [comment]
In the code. I just try to force the model to reach the limit 4096 but is just showing less in the output. I am working with prompflow and prompty using python scripts. Maybe you have any suggest of how to handle the output limits using this tools?

{
  "promptflow": "1.11.0",
  "promptflow-azure": "1.12.0",
  "promptflow-core": "1.11.0",
  "promptflow-devkit": "1.11.0",
  "promptflow-tracing": "1.11.0"
}

**Comment by sethjuarez** [comment]
As a fallback, we've released a smaller more compact [prompty runtime](https://pypi.org/project/prompty/) for you to try. Let me know if this solves the issue.
