### ISSUE TITLE
New Prompty created file has str data type instead of string

### ISSUE THREAD

**Issue by swarchitex** [microsoft/prompty#4]
Created my first Prompty file, and leaving untouched the text on the new window, returns: **ValueError: 'str' is not a valid ValueType** and will not launch.

Changed **str** to **string** in the newly created file and now test chat page doe launch.

**Comment by sethjuarez** [comment]
Oh interesting! I think in this case we should be more explicit about the valid type names here - good catch.

**Comment by wayliums** [comment]
@swarchitex just checking what are you using for testing? Directly QuickRun in the extension or something else?

**Comment by wayliums** [comment]
oh nvm, i can repro in langchain. let me fix it.

**Comment by wayliums** [comment]
fixed, extension updated
