### ISSUE TITLE
New Prompty file on right click VS Code File explorer not creating the file on the folder.

### ISSUE THREAD

**Issue by anuraj** [microsoft/prompty#52]
I am creating a prompty file in an ASP.NET Core Web API project. When right clicking on the File Explorer and selecting the New Prompty , it will create the prompty file, and open it, but it is not created in the project root, instead it is created in the parent folder.

![image](https://github.com/user-attachments/assets/ea54cc75-d6b0-4b96-bc33-ee4e0024c950)

**Comment by sethjuarez** [comment]
In general it should create the prompty file in the selected folder - is this your experience?

**Comment by anuraj** [comment]
Yes, that is the expected behavior right?

**Comment by sethjuarez** [comment]
Yes it is! Is it not doing that?
