### ISSUE TITLE
Prompty fails to load in SemanticKernel when using  json_object response format

### ISSUE THREAD

**Issue by nir-schleyen** [microsoft/prompty#53]
This is the correct yaml and works via VSCode, yet will fail to load in .net:
    response_format:
        type: json_object
        
As a workaround, I use this for now:
response_format: json_object
This would load and work in .net, but would fail in VSCode....

**Comment by sethjuarez** [comment]
OOF - we are working on having a more consistent experience across languages.

**Comment by nir-schleyen** [comment]
Any update on this? Looking on c# Prompty code, fix shouldn't be that hard

**Comment by sethjuarez** [comment]
Tagging @cassiebreviu

**Comment by cassiebreviu** [comment]
This should be filed with Semantic Kernal. It's likely that attribute hasnt been implemented in the SK yet.

**Comment by nir-schleyen** [comment]
@sethjuarez, @cassiebreviu , I created this PR in SK to fix the yaml schma issue:
https://github.com/microsoft/semantic-kernel/pull/8168/files

**Comment by sethjuarez** [comment]
Looks like it was accepted!!! Will close this issue for now barring any other comments.
