### ISSUE TITLE
Conflictive configuration between Prompty and Prompt flow

### ISSUE THREAD

**Issue by vincentgiraud** [microsoft/prompty#54]
**Describe the bug**

The model configuration in the Prompty file is conflicting with the model configuration in Prompty setttings

**How To Reproduce the bug**
1. Right click 'New Prompty'
2. Set your `azure_endpoint` and `azure_deployment`
3. Click 'Run' it works
4. Change the Prompt model configuration (bottom right drop down) to another model
5. Click 'Run' it fails (because it is picking up other creds)

Note: clicking 'Test' will run the Prompty file config NOT the Prompty settings model config (clicking 'Run').
This could end up in confusion while comparing results between 'Run' and 'Test'.

**Ideal solution**
Get rid of Prompty file configuration. When 'Add Promp flow code', pick up the Prompty settings configuration and generate the Python code:
```python
  # pick up Prompty settings configuration
  model_config = get_prompty_config(name, model_config_path)

  # load prompty as a flow with optional 
  flow = Prompty.load(path_to_prompty, model_config=model_config)
```
For this, this line under `_flow.py` will likely have to be altered to catter for it:
```python
   configs = update_dict_recursively(configs, resolve_references(kwargs, base_path=path.parent))
```
Maybe it is already possible but I didn't find in the [flow documentation](https://microsoft.github.io/promptflow/how-to-guides/develop-a-flex-flow/model-config.html).

**Environment Information**
 - Prompty extension version: v0.1.2024060511
 - Operating System: Windows 11
 - Python version : 3.11.9
 - VS Code version: 1.91.1
 - Prompt Flow extension version: v1.20.1

**Comment by vincentgiraud** [comment]
After further testing, to work with:

- pf CLI or SDK:

![Screenshot 2024-08-08 122514](https://github.com/user-attachments/assets/e078d59e-8731-4028-a6eb-9c9cdc4a8219)

- Prompty VSC UI along with a model configuration unde `prompty.modelConfigurations` settings (don't forget the `api_key`):

![Screenshot 2024-08-08 123110](https://github.com/user-attachments/assets/748a1164-a8ad-4fcc-b317-cd869b42ae96)

**Comment by sethjuarez** [comment]
I've released a more up to date standalone prompty runtime. It should be a bit more consistent. I am planning on creating a PR and adding it to PromptFlow. This way we can be a bit more agile on prompty issues. You can find it here: [https://pypi.org/project/prompty/](https://pypi.org/project/prompty/). Working on docs for it today.

**Comment by vincentgiraud** [comment]
On the standalone version, I've tried to use a tracer but this in the [doc](https://pypi.org/project/prompty/) won't work:
```python
from prompty.tracer import Trace, PromptyTracer
# add default tracer
Trace.add_tracerTrace.add_tracer("prompty", PromptyTracer("path/to/trace/dir"))
```
I guess more something around this lines:
```python
from prompty.tracer import Tracer, PromptyTracer
# add default tracer
Tracer.add("prompty", PromptyTracer("path/to/trace/dir"))
```
but stil an issue with PromptyTracer not being callable. 

Also, I couldn't get the prompty CLI to work after the pip installation.

**Comment by sethjuarez** [comment]
Apologies - I was going through the mental process of how to make the tracing better. The latest package has the final approach (just a context based hook function). I added the instructions on the [package README](https://pypi.org/project/prompty/).
