### ISSUE TITLE
"Add Prompt flow Code" won't format image input properly

### ISSUE THREAD

**Issue by vincentgiraud** [microsoft/prompty#56]
**Describe the bug**

When right-clicking "Add Prompt flow Code" on a prompty file, if a markdown image is referenced in the prompt e.g.

```markdown
...
sample:
  input_image: ./images/test_image.jpg
...
user:
![image]({{input_image}})
```
then the generated code will be:
```python
...
json_input = '''{
  "input_image": "./images/test_image.jpg"
}'''
...
```
The image path string won't be converted into an image because the data representation and mime types are missing and mandatory. But adding them as an object following the [documented format](https://learn.microsoft.com/en-us/azure/machine-learning/prompt-flow/how-to-process-image?view=azureml-api-2#create-a-batch-run-using-image-data) won't work either because the prompt flow conversion function only parses strings and uses a regex to extract the types.

As a result, the model answers that it cannot read the image, or worse, answers making a guess based on the filename :)

**Workaround**

Add the data representation and mime types as prefix in the image path string:
```python
...
json_input = '''{
  "input_image": "data:image/jpg;path:./images/test_image.jpg"
}'''
...
```

**Environment Information**
 - Prompty extension version: v0.1.2024060511
 - Operating System: Windows 11
 - Python version : 3.11.9
 - VS Code version: 1.91.1
 - Prompt Flow extension version: v1.20.1
 - LLM: Azure gpt-4o v2024-05-13

**Comment by sethjuarez** [comment]
Sorry this took a bit - I released a version of a standalone [prompty runtime](https://pypi.org/project/prompty/) that addresses this issue. Let me know if this works!

**Comment by vincentgiraud** [comment]
Thanks, the image is now converted with the standalone runtime. 

I couldn't get the CLI to work though (term not recognized in pwsh).

**Comment by sethjuarez** [comment]
Yeah - it was a tad bit broken with the last release. It should work now.

**Comment by vincentgiraud** [comment]
> Yeah - it was a tad bit broken with the last release. It should work now.

As of version 0.1.15 the `prompty` CLI term is still not recognized :/

**Comment by sethjuarez** [comment]
OK! This has been fixed
