### ISSUE TITLE
Prompty documentation link is broken

### ISSUE THREAD

**Issue by iemejia** [microsoft/prompty#59]
When you see the [Prompty extension in the VS Code Marketplace](https://marketplace.visualstudio.com/items?itemName=ms-toolsai.prompty), there is a [link to the documentation](https://microsoft.github.io/prompty/). When you click on the link you end up in a 404 error page.

![promptyerrorscreenshot](https://github.com/user-attachments/assets/b5757dc8-7611-4bf3-b3b5-8317b47cc44f)

**Comment by revodavid** [comment]
Addressed by PR #71
