### ISSUE TITLE
why not support simple python projects? 

### ISSUE THREAD

**Issue by nickknyc** [microsoft/prompty#6]
why do you need to be using semantic kernel or prompt flow?

why cant it work with a simple python script.. i must be missing something.

**Comment by sethjuarez** [comment]
That's an awesome question. In general, we need to have a runtime to execute these files in code. In theory you could definitely write your own prompty loader and execute it for sure. We thought it would be easier to do that in prompt flow. Are you suggesting we should have a standalone prompty library?

**Comment by nickknyc** [comment]
absolutely. otherwise, it seems to be an "azure-only" tool - and you didn't mention autogen 😏

what would really make this sing would be a lightweight prompt library manager. seeing as it is all. md and frontmatter, i was thinking of using obsidian to manage them.... could be pretty powerful..

Sent from Surface Duo
________________________________

**Comment by mattgotteiner** [comment]
Looks like there's some parsing code in the promptflow library
https://github.com/microsoft/promptflow/blob/1826b3e55e36132281d68e1765f43aa13b6e5241/src/promptflow-core/promptflow/core/_flow.py#L218

Any chance that we can get a local package that allows us to parse prompty files so we can write our own executors? For example, I might want to take a prompty that was meant for gpt-35-turbo but run it using a custom configuration using a foundation model I deployed on AI Studio

**Comment by sethjuarez** [comment]
We are working on getting some of our internal community packages released.

**Comment by sethjuarez** [comment]
We've released an early version of the prompty package on [PyPI](https://pypi.org/project/prompty/). I am working out a couple of things and am hoping to have something by EOW

**Comment by nextedoff** [comment]
> We've released an early version of the prompty package on [PyPI](https://pypi.org/project/prompty/). I am working out a couple of things and am hoping to have something by EOW

I have a slightly unrelated question, but is there any way to register custom executors with Prompty while using promptflow?

**Comment by sethjuarez** [comment]
Not at the moment. Currently promptflow uses its own execution mechanism and not the factory pattern we use in prompty. The prompty package lives at a lower level than promptflow. Building your own executor is not super difficult though.

**Comment by sethjuarez** [comment]
Will close this - we've set up the [Python runtime code](https://github.com/microsoft/prompty/tree/main/runtime/prompty) in this repo and it auto deploys to [PyPI](https://pypi.org/project/prompty/) when tagged. Working on docs still.
