### ISSUE TITLE
Documentation for command-line "prompty" script

### ISSUE THREAD

**Issue by revodavid** [microsoft/prompty#72]
The [prompty python package](https://pypi.org/project/prompty/) apparently installs a CLI script to run prompty files directly:
```
prompty -s path/to/prompty/file
```

This useful feature isn't discussed in the docs. Also it would be useful to discuss:
* How to install the python package
* How to get this script added to $PATH. (In my experience, I get `bash: prompty: command not found`)
* How to pass new values for the input parameters via the CLI

**Comment by sethjuarez** [comment]
In general, it is installed a script in the python environment. If the python env is active, then the script should be accessible. This is def a docs issue though.

**Comment by sethjuarez** [comment]
Made corrections in `0.1.17`
