### ISSUE TITLE
Add a devcontainer to this repo to support CodeSpaces

### ISSUE THREAD

**Issue by revodavid** [microsoft/prompty#78]
It would be great if a user could launch a codespace on this repo to test out prompty in a controlled environment. It could support the following use cases:

**Quick test with an Azure OPENAI endpoint already deployed:**
* Launch CodeSpace on this repo
* In VS code, right-click and choose "New Prompty" to create `basic.prompty`
* Update the `azure_deployment:` field in `basic.prompty` with the endpoint of the deployed Azure OpenAI service
* Click "run" button in `basic.prompty` to see output
* Open terminal, execute `prompty -s basic.prompty` to see output.

**Deploy an Azure OPENAI endpoint and test**
* Launch CodeSpace on this repo
* Open terminal and:
  * `azd login --use-device-code` to log into a subscription
  * `azd up` to deploy a gpt-4o endpoint (and set the AZURE_OPENAI_ENDPOINT environment variable)
* In VS code, right-click and choose "New Prompty" to create `basic.prompty`
* Update the `azure_deployment:` field in `basic.prompty` with the endpoint called "gpt-4o"
* Click "run" button in `basic.prompty` to see output
* Open terminal, execute `prompty -s basic.prompty` to see output.

**Comment by revodavid** [comment]
The devcontainer would need to be based on a Python3 image and install:
 * Python package `prompty[azure]`
 * VS Code extension `prompty`

**Comment by revodavid** [comment]
It would also be good to configure the `basic.prompty` file created by New Prompty to use a GitHub Models endpoint, as a free endpoint that anyone can create.

**Comment by sethjuarez** [comment]
In general this repo represents the actual runtime code as well as the website. It is not intended as a sample on how _to use_ prompty. The latest extension allows for quick creation of prompty files directly from GitHub models now. Hope this helps!
