### ISSUE TITLE
Error: 400 status code (no body)

### ISSUE THREAD

**Issue by batemansogq** [microsoft/prompty#8]
Running the default Prompty template, post;

1. azd auth login
2. subscription set

update the prompty for the endpoint, deployment name and max tokens - run get the error message of "Error: 400 status code (no body)"

see attached screenshots - 
![prompty1](https://github.com/microsoft/prompty/assets/15646722/c2c9646d-5a32-45c4-88b7-d580dd38ce9a)
![prompty2](https://github.com/microsoft/prompty/assets/15646722/42c84473-f1aa-495d-827d-40c57c0f3908)
![prompty3](https://github.com/microsoft/prompty/assets/15646722/e2b82e3b-b8bb-48f4-b5c6-61ae42381651)

Any ideas?

**Comment by wayliums** [comment]
hmm, looks like the model endpoint doesn't understand the payload, looks weird, which model is it? GPT35 turbo?
Have you tried creating another endpoint and test with that?

**Comment by wayliums** [comment]
also, can you try using api key, and see if that's working?

**Comment by fjuradom98** [comment]
Hello @wayliums @batemansogq I am having the same issue, with the basic example. But i see that you already got an answer in the first time, and in the second iteration shows the error, correct?
I have the issue at the first time, i am trying to configure my local environment

**Comment by batemansogq** [comment]
@wayliums - current model 
![image](https://github.com/microsoft/prompty/assets/15646722/9bff66cc-e52f-4726-8ffa-ef84e58d1059)

**Comment by batemansogq** [comment]
![image](https://github.com/microsoft/prompty/assets/15646722/6e483447-a57b-485f-a521-72b654a52c78)
@wayliums 
- changing the model/deployment doesnt change the outcome
- with the API key addition, it works for either model/deployment.

**Comment by wayliums** [comment]
@batemansogq  you mean if you remove the api_key, using AAD it's not working? And is it the same for all models?

Btw if you have to use API key, I suggest you use 
${env:API_KEY}, it'll try to find and load .env file in 
* same folder of .prompty file
* VSCode workspace root.
