### ISSUE TITLE
when running prompty through the vs code extension, can't use a json file as a sample

### ISSUE THREAD

**Issue by ranish8080** [microsoft/prompty#81]
I'm running prompty through the vs code extension. My prompty configuration has a complex input which I want to load from a json file. This doesn't seem to be supported by the extension

**Comment by sethjuarez** [comment]
Great question - have you tried something like [this](https://github.com/Azure-Samples/contoso-creative-writer/blob/main/src/api/agents/writer/writer.prompty#L14-L20)?

**Comment by ranish8080** [comment]
It doesn't work. Interestingly enough when running the same .prompty file through the promptflow VS code extension through the _test_ button, it works:
<img width="519" alt="image" src="https://github.com/user-attachments/assets/76911cc3-fda7-48d0-9e77-d1027f5fafa0">

**Comment by sethjuarez** [comment]
Can you describe what you are doing and what error you are getting?

**Comment by valegrajales** [comment]
I found that prompflow tries to search for files located in folders with lowercase, so, if you have a project in prompflow and the json files are located in folder with some uppercase prompflow can't file the file to be included (replaced) in prompty. I solve the problem renaming my folder to lowercase (I'm using WSL 2).

**Comment by sethjuarez** [comment]
Marking as closed - happy to reopen if there are isssues.
